title: Strikethrough Generator | whdzera
username: whdzera
email: whdzera@gmail.com
baseurl: "/strikethrough-generator"
url: "" 
twitter_username: whdzera
github_username:  rokhimin/jekyll
donate_username: whdzera
